### ISSUE TITLE
setImmediate is not defined in most browsers

### ISSUE THREAD

**Issue by quotquot** [NodeGuy/channel#1]
The project description says the library can be used in browsers.  Yet, unless I'm missing something, it uses the "setImmediate" function which is not defined in chromium 63 and, according to MDN [1], is hardly defined in any browser at all.

[1] https://developer.mozilla.org/en-US/docs/Web/API/Window/setImmediate

**Comment by NodeGuy** [comment]
Nice catch!  I'm leaving for a trip tomorrow and will fix this when I return in a couple of weeks.
