### ISSUE TITLE
Make it possible to set fixed buffer size

### ISSUE THREAD

**Issue by ufukomer** [NodeGuy/channel#16]
Can I set fixed buffer size like 1? Or can I at least get the latest value in the channel and remove the rest?

If not, one solution that comes to my mind is to use shift() before each push(). Do you think it is a good idea? Like:

```js
for (;;) {
  // ...
  channel.shift();
  channel.push(value);
  // ...
}
```

**Comment by ufukomer** [comment]
I've realized that the above is not a good solution. Does this word?

```js
await chan.slice(-1).shift();
```

What I am not sure here is that I am continuously pushing new values into channel without using await. So, my question is that: Is the code above removing all the elements inside the channel? It might be a memory leakage at some point.

**Comment by NodeGuy** [comment]
I don't understand what problem you're trying to solve.  What is it that you're wanting to accomplish?

**Comment by ufukomer** [comment]
I am pushing items into channel continuously without _await_ (without waiting it to be shifted), thus, lots of items are being accumulated inside the channel however I only want the latest item pushed to be exist in the channel. @NodeGuy

**Comment by NodeGuy** [comment]
This library was not designed for that use case.  You may have better luck using a different library.

**Comment by ufukomer** [comment]
@NodeGuy thanks! Please tell me if you have a suggestion.
