### ISSUE TITLE
TypeScript usage?

### ISSUE THREAD

**Issue by milibopp** [NodeGuy/channel#18]
I tried using channel with TypeScript and found it to fail type checking.

With the following code (mostly from the README):

```typescript
import Channel = require("@nodeguy/channel");
import assert = require("assert");

const channel = Channel();

const send = async () => {
  await channel.push(42);
  await channel.close();
};

const receive = async () => {
  assert.equal(await channel.shift(), 42);
  assert.equal(await channel.shift(), undefined);
};

(async () => {
  await Promise.all([send(), receive()]);
})();
```

I ran the script with `ts-node` and got this type error:

```
TSError: ⨯ Unable to compile TypeScript:
foo.ts:5:17 - error TS2349: This expression is not callable.
  Type 'typeof import("redacted/path/node_modules/@nodeguy/channel/lib/index")' has no call signatures.

5 const channel = Channel();
                  ~~~~~~~
```

It runs fine, when I add `// @ts-ignore` before the offending line, so it seems the module itself is fine? Still I'd like not to use that hack and have it typecheck properly ;)

Am I just using this wrong? Perhaps @graup could weigh in, as they added the type definitions.

**Comment by graup** [comment]
Are you sure this isn't an issue with your setup? Do you get the same error when using ESM-style imports?

Copy-pasting your code (changing the imports to ESM style) to Typescript Playground, I don't get any errors there.

[See Typescript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAYQBYEMB2aCmAbOAzKCEOAIgAE0IATTAcwFcBPAegGNUMcSBuAWAChQkWHBQBnMZhEEipcZNg8BA1hDRj47dFlwBeRBx0AKAJR9+KtRriS0VOPvGM0rOKYcA+OAG8BcUQDuKMCahjgAdGD0YkhGACwATGZ+gcGh2hGs2BCSpuYAvuaW6vBQmKyYwABumA6iYs6u7rpevvz+8lIw4ZgAjvQo2EYoQSFwWpzY4THAeDCmADRwicnt9QrdfQNDI2njYVMzc4tw9HaYeMBYVKuFyvzDDS5uJp4+KbtjAAqEIMCS4UGQwA2rYqCcyhVqphTABdW4mPJAA)

**Comment by milibopp** [comment]
Ah, that's it. Thanks for questioning it. I needed to use the `esModuleInterop` compiler option for TypeScript to accept that import, but now it works.
